// lib/src/core/database/database_provider.dart

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:verse_reader/src/core/database/app_database.dart';

// This file is generated by Riverpod to provide the necessary provider code
part 'database_provider.g.dart';

/// A Riverpod provider that manages the singleton instance of [AppDatabase].
/// 
/// The `@riverpod` annotation automatically generates the provider code.
/// `keepAlive: true` ensures that the database instance persists throughout
/// the app's lifecycle, preventing unnecessary recreations when the widget
/// tree rebuilds or when the provider is no longer being listened to.
@Riverpod(keepAlive: true)
AppDatabase appDatabase(Ref ref) {
  // Create and return a new instance of AppDatabase.
  // The provider will ensure this is a singleton.
  return AppDatabase();
}
